/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Proj2;

import org.checkerframework.checker.units.qual.A;
import org.junit.jupiter.api.Test;

import java.io.InputStream;
import java.io.PrintStream;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.math.BigDecimal;
import java.beans.Transient;
import java.io.ByteArrayInputStream;
import java.nio.charset.StandardCharsets;
import java.time.format.DateTimeFormatter;
import java.time.*;

import java.io.File;
import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;

class CinemaTest {
    /*
    @Test
    public void mainTest(){
        InputStream stdin = System.in;
        System.setIn(new ByteArrayInputStream("3\n4\n".getBytes()));

        ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
        PrintStream ps = new PrintStream(byteArrayOutputStream);
        PrintStream stdout = System.out;
        System.setOut(ps);

        UserInputExample.main(new String[0]);

        System.setIn(stdin);
        System.setOut(stdout);

        String outputText = byteArrayOutputStream.toString();
        String key = "output:";
        String output = outputText.substring(outputText.indexOf(key) + key.length()).trim();
        Assert.assertEquals(output, "7");
    }*/

    @Test
    public void testNameSearch(){
        int id = 1;
        String name = "Steve Buscemi 10 Hour Compilation";
        String synopsis = "As above"; //plot
        String rating = "10"; //rating
        String releaseDate = "10/10/10"; //?
        ArrayList<String> cast = new ArrayList<>(); //people
        Movie plsman = new Movie(id, name, synopsis, rating, releaseDate, cast);

        ArrayList<Movie> movv = new ArrayList<>();
        movv.add(plsman);
        Movie foundmov = Cinema.searchMovie("Steve Buscemi 10 Hour Compilation",movv);
        assertEquals(plsman,foundmov,"Movies are not Equal");
    }
    /*
    @Test
    public void userInputTestEverythingFIne() {
        //mimic userinput
        ByteArrayInputStream inputStream = new ByteArrayInputStream("3\n4\n".getBytes());
        ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
        PrintStream ps = new PrintStream(byteArrayOutputStream);
        UserInputExample userInputExample = new UserInputExample(inputStream, ps);

        //call method
        moviearray = userInputExample.movie_init();
        // All output to prnt is sent to ps
        // Return output is the same
        String outputText = byteArrayOutputStream.toString();
        String key = "output:";
        String output = outputText.substring(outputText.indexOf(key) + key.length()).trim();

        //assert prnt output = expect
        Assert.assertEquals(output, "7");
        //assert actual return = expect

    }
    */

    @Test
    public void cardTest(){
        String cardNumber = "12345";
        String cardHolderName = "TestName";

        Card testCard = new Card(cardNumber, cardHolderName);
        assertEquals(testCard.getCardNumber(), "12345", "Card number returned is incorrect");
        testCard.setCardNumber("54321");
        assertEquals(testCard.getCardNumber(), "54321", "Card number returned is incorrect");
        assertEquals(testCard.getCardHolderName(), "TestName", "Card holder name returned is incorrect");
        testCard.setCardNumber("New TestName");
        assertEquals(testCard.getCardNumber(), "New TestName", "Card holder name returned is incorrect");
    }

    @Test
    public void giftcardTest(){
        String giftCardNumber = "1875890093350513";
        boolean redeemed = false;

        GiftCard testGiftCard = new GiftCard(giftCardNumber, redeemed);
        assertEquals(testGiftCard.getGiftCardNumber(),"1875890093350513", "Gift card number returned is incorrect");
        testGiftCard.setGiftCardNumber("1875890093351111");
        assertEquals(testGiftCard.getGiftCardNumber(),"1875890093351111", "Gift card number returned is incorrect");
        assertFalse(testGiftCard.isRedeemed(), "Gift card is considered to be redeemed, yet it has not been");
        testGiftCard.setRedeemed(true);
        assertTrue(testGiftCard.isRedeemed(), "Gift card is considered to not be redeemed, yet it has been");
    }

    @Test
    public void getUserTest(){
        String input = "Broskin\n"       // "Wrong number, try again."
                + "YOYO\n";
        InputStream is = new ByteArrayInputStream(input.getBytes(StandardCharsets.UTF_8));
        UserInput u = new UserInput(is, System.out);
        ArrayList<Customer> customers = new ArrayList<Customer>();
        Customer g = new Customer("Broskin", "YOYO", null,null);
        customers.add(g);
        assertTrue(u.promptLogin("Broskin","YOYO",customers));
        u.promptLogin("JohnJohn", "Doe", customers);
        u.promptLogin("Broskin", "Doe", customers);
        }

    @Test
    public void movieTest(){
        int id = 1;
        String name = "Movie";
        String synopsis = "Synopsis";
        String rating = "G";
        String releaseDate = "10/10/2010";
        String actor1 = "Matt Damon";
        String actor2 = "Maaaaaatt Daaaaaamon";

        ArrayList<String> cast = new ArrayList<String>();
        cast.add(actor1);
        cast.add(actor2);

        Movie testMovie = new Movie(id, name, synopsis, rating, releaseDate, cast);

        assertEquals(testMovie.getId(), 1, "Movie ID returned is incorrect");
        assertEquals(testMovie.getName(), "Movie", "Movie name returned is incorrect");
        testMovie.setName("Finding Nemo");
        assertEquals(testMovie.getName(), "Finding Nemo", "Movie name returned is incorrect");
        assertEquals(testMovie.getSynopsis(), "Synopsis", "Movie synopsis returned is incorrect");
        testMovie.setSynopsis("This movie is about fish");
        assertEquals(testMovie.getSynopsis(), "This movie is about fish", "Movie synopsis returned is incorrect");
        assertEquals(testMovie.getRating(), "G", "Movie rating returned is incorrect");
        testMovie.setRating("M");
        assertEquals(testMovie.getRating(), "M", "Movie rating returned is incorrect");
        assertEquals(testMovie.getReleaseDate(), "10/10/2010","Movie release date returned is incorrect");
        testMovie.setReleaseDate("10/10/2021");
        assertEquals(testMovie.getReleaseDate(), "10/10/2021","Movie release date returned is incorrect");

        assertEquals(testMovie.getCast(), cast, "Cast returned is incorrect");
        ArrayList<String> updatedCast = new ArrayList<String>();
        String actor3 = "Chad";
        String actor4 = "Lachlan";
        updatedCast.add(actor3);
        updatedCast.add(actor4);
        testMovie.setCast(updatedCast);
        assertEquals(testMovie.getCast(), updatedCast, "Cast returned is incorrect");
    }

    @Test
    public void customerTest(){
        String username = "username";
        String password = "password";

        String cardNumber1 = "40691";
        String cardHolderName1 = "Charles";
        String cardNumber2 = "42689";
        String cardHolderName2 = "Sergio";
        Card testCard1 = new Card(cardNumber1, cardHolderName1);
        Card testCard2 = new Card(cardNumber2, cardHolderName2);
        ArrayList<Card> testCards = new ArrayList<Card>();
        testCards.add(testCard1);
        testCards.add(testCard2);
        String testTicket1 = "Ticket1";
        String testTicket2 = "Ticket2";
        ArrayList<String> testTickets = new ArrayList<String>();
        testTickets.add(testTicket1);
        testTickets.add(testTicket2);

        Customer testCustomer = new Customer(username, password, testCards, testTickets);

        assertEquals(testCustomer.getUsername(), "username", "Username returned is incorrect");
        testCustomer.setUsername("newUsername");
        assertEquals(testCustomer.getUsername(), "newUsername", "Username returned is incorrect");
        assertEquals(testCustomer.getPassword(), "password", "Password returned is incorrect");
        testCustomer.setPassword("newPassword");
        assertEquals(testCustomer.getPassword(), "newPassword", "Password returned is incorrect");

        assertEquals(testCustomer.getCards(), testCards, "Card list returned is incorrect");
        String cardNumber3= "12345";
        String cardHolderName3 = "Hamish";
        Card testCard3 = new Card(cardNumber3, cardHolderName3);
        ArrayList<Card> testCardsUpdated = new ArrayList<Card>();
        testCardsUpdated.add(testCard3);
        testCustomer.setCards(testCardsUpdated);
        assertEquals(testCustomer.getCards(), testCardsUpdated, "Card list returned is incorrect");
        String cardNumber4= "54321";
        String cardHolderName4 = "Jackson";
        Card testCard4 = new Card(cardNumber4, cardHolderName4);
        testCardsUpdated.add(testCard4);
        testCustomer.addCard(testCard4);
        assertEquals(testCustomer.getCards(), testCardsUpdated, "Card list returned is incorrect");

        assertEquals(testCustomer.getTickets(), testTickets, "Ticket list returned is incorrect");
        String testTicket3 = "Ticket3";
        ArrayList<String> testTicketsUpdated = new ArrayList<String>();
        testTicketsUpdated.add(testTicket3);
        testCustomer.setTickets(testTicketsUpdated);
        assertEquals(testCustomer.getTickets(), testTicketsUpdated, "Ticket list returned is incorrect");
        String testTicket4 = "Ticket4";
        testTicketsUpdated.add(testTicket4);
        testCustomer.addTicket(testTicket4);
        assertEquals(testCustomer.getTickets(), testTicketsUpdated, "Ticket list returned is incorrect");

    }

    @Test
    public void cinemaTest(){
        int c_id = 1;
        int m_id = 1;
        String name = "Movie";
        String synopsis = "Synopsis";
        String rating = "G";
        String releaseDate = "10/10/2010";
        String actor1 = "Matt Damon";
        String actor2 = "Maaaaaatt Daaaaaamon";
        ArrayList<String> cast = new ArrayList<String>();
        cast.add(actor1);
        cast.add(actor2);
        Movie testMovie = new Movie(m_id, name, synopsis, rating, releaseDate, cast);
        ArrayList<Movie> moviesParent = new ArrayList<Movie>();
        moviesParent.add(testMovie);
        Card card = new Card("", "");

        String c_name = "Event";
        String location = "Bondi Junction";

        int f_seatsOpen = 40;
        int f_seatsCapacity = 50;
        int m_seatsOpen = 40;
        int m_seatsCapacity = 50;
        int r_seatsOpen = 40;
        int r_seatsCapacity = 50;
        String day = "Monday";
        LocalTime time = LocalTime.of(11, 30, 00, 00);
        String screenSize = "Gold";
        BigDecimal basePrice = new BigDecimal("20");
        BigDecimal ticketPrice = new BigDecimal("1.6");

        MovieInstance movInst = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                                                    day, time, screenSize, basePrice);

        ArrayList<MovieInstance> movies = new ArrayList<MovieInstance>();
        movies.add(movInst);

        int transactionNo = 1;
        String username = "username";
        String password = "password";

        String cardNumber1 = "40691";
        String cardHolderName1 = "username";
        String cardNumber2 = "42689";
        String cardHolderName2 = "Sergio";
        Card testCard1 = new Card(cardNumber1, cardHolderName1);
        Card testCard2 = new Card(cardNumber2, cardHolderName2);
        ArrayList<Card> testCards = new ArrayList<Card>();
        ArrayList<GiftCard> validGiftCards = new ArrayList<GiftCard>();
        validGiftCards.add(new GiftCard("1234567891123456GC", false));
        validGiftCards.add(new GiftCard("1234567891123457GC", true));
        testCards.add(testCard1);
        testCards.add(testCard2);
        String testTicket1 = "Ticket1";
        String testTicket2 = "Ticket2";
        ArrayList<String> testTickets = new ArrayList<String>();
        testTickets.add(testTicket1);
        testTickets.add(testTicket2);

        Customer testCustomer = new Customer(username, password, testCards, testTickets);
        ArrayList<Customer> customers = new ArrayList<Customer>();
        customers.add(testCustomer);

        Cinema testCinema = new Cinema(c_id, c_name, location,movies, moviesParent);

        assertEquals(testCinema.getName(), c_name, "Cinema name returned is incorrect");
        testCinema.setName("Hoyts");
        assertEquals(testCinema.getName(), "Hoyts", "Cinema name returned is incorrect");
        assertEquals(testCinema.getTicketReceipt(), "Cinema ID: 1\nTransaction No.: 1\n");
        assertEquals(testCinema.getLocation(), location, "Cinema location returned is incorrect");
        testCinema.setLocation("Wyoming");
        assertEquals(testCinema.getLocation(), "Wyoming", "Cinema location returned is incorrect");

        assertEquals(testCinema.searchMovie("Movie", moviesParent), testMovie, "Movie search failed");
        assertEquals(testCinema.searchMovie("Incorrect name", moviesParent), null, "Movie search failed");

        assertEquals(testCinema.getMovieParents(), moviesParent, "Movie parents list returned is incorrect");
        assertEquals(testCinema.getMovies(), movies, "Movies list returned is incorrect");

        int newc_id = 2;
        int newm_id = 2;
        String newName = "Movie";
        String newSynopsis = "Synopsis";
        String newRating = "G";
        String newReleaseDate = "10/10/2010";
        String actor3 = "Leo Di Caprio";
        String actor4 = "Ched";
        ArrayList<String> newCast = new ArrayList<String>();
        newCast.add(actor3);
        newCast.add(actor4);
        Movie newMovie = new Movie(newm_id, newName, newSynopsis, newRating, newReleaseDate, newCast);

        int f_seatsCapacity1 = 50;
        int m_seatsCapacity1 = 50;
        int r_seatsCapacity1 = 50;
        String newDay = "Monday";
        LocalTime newTime = LocalTime.of(11, 30, 00, 00);
        String newScreenSize = "Gold";
        BigDecimal newBasePrice = new BigDecimal("20");
        BigDecimal newTicketPrice = new BigDecimal("1.6");

        MovieInstance newMovInst = new MovieInstance(newm_id, newc_id, newMovie, f_seatsCapacity1, m_seatsCapacity1, r_seatsCapacity1,
                newDay, newTime, newScreenSize, newBasePrice);

        ArrayList<MovieInstance> movies1 = new ArrayList<MovieInstance>();
        movies1.add(newMovInst);
        testCinema.setMovies(movies1);
        assertEquals(testCinema.getMovies(), movies1, "Movies list returned is incorrect");

        assertEquals(testCinema.getId(), c_id, "Cinema ID returned is incorrect");

         String input = "3\n0\n0\n0\n" + "1\n" + "1\n" + "1\n" + "2\n" + "1234567891123456GC\n";
         InputStream is = new ByteArrayInputStream(input.getBytes(StandardCharsets.UTF_8));
         UserInput u = new UserInput(is, System.out);
        card = u.book(newMovInst,testCinema,testCards,validGiftCards,testCustomer, card);

        String input2 = "3\n0\n0\n0\n" + "1\n" + "1\n" + "1\n" + "2\n" + "1234567891123457GC\n";
        InputStream is2 = new ByteArrayInputStream(input2.getBytes(StandardCharsets.UTF_8));
        UserInput u2 = new UserInput(is2, System.out);
        card = u2.book(newMovInst,testCinema,testCards,validGiftCards,testCustomer, card);

        String input3 = "3\n0\n0\n0\n" + "1\n" + "1\n" + "1\n" + "2\n" + "1234567891123458GC\n";
        InputStream is3 = new ByteArrayInputStream(input3.getBytes(StandardCharsets.UTF_8));
        UserInput u3 = new UserInput(is3, System.out);
        card = u3.book(newMovInst,testCinema,testCards,validGiftCards,testCustomer, card);

        String input4 = "3\n0\n0\n0\n" + "cancel\n";
        InputStream is4 = new ByteArrayInputStream(input4.getBytes(StandardCharsets.UTF_8));
        UserInput u4 = new UserInput(is4, System.out);
        card = u4.book(newMovInst,testCinema,testCards,validGiftCards,testCustomer, card);

        String input5 = "3\n0\n0\n0\n" + "1\n" + "cancel\n";
        InputStream is5 = new ByteArrayInputStream(input5.getBytes(StandardCharsets.UTF_8));
        UserInput u5 = new UserInput(is5, System.out);
        card = u5.book(newMovInst,testCinema,testCards,validGiftCards,testCustomer, card);

        String input6 = "3\n0\n0\n0\n" + "1\n" + "1\n" + "cancel\n";
        InputStream is6 = new ByteArrayInputStream(input6.getBytes(StandardCharsets.UTF_8));
        UserInput u6 = new UserInput(is6, System.out);
        card = u6.book(newMovInst,testCinema,testCards,validGiftCards,testCustomer, card);

        String input7 = "3\n0\n0\n0\n" + "1\n" + "1\n" + "1\n" + "2\n" + "cancel\n";
        InputStream is7 = new ByteArrayInputStream(input7.getBytes(StandardCharsets.UTF_8));
        UserInput u7 = new UserInput(is7, System.out);
        card = u7.book(newMovInst,testCinema,testCards,validGiftCards,testCustomer, card);

        String input8 = "3\n0\n0\n0\n" + "1\n" + "1\n" + "1\n" + "cancel\n";
        InputStream is8 = new ByteArrayInputStream(input8.getBytes(StandardCharsets.UTF_8));
        UserInput u8 = new UserInput(is8, System.out);
        u8.book(newMovInst,testCinema,testCards,validGiftCards,testCustomer,card);
        assertEquals(newMovInst.getMovieDetails(), """
        
        Movie
        Synopsis: Synopsis
        Rating: G
        Release Date: 10/10/2010
        Cast: Leo Di Caprio, Ched""", "Invalid Response");
    }

    @Test
    public void setCardHolderNameTest(){
        String cardNumber1 = "40691";
        String cardHolderName1 = "Charles";
        Card testCard1 = new Card(cardNumber1, cardHolderName1);
        testCard1.setCardHolderName("jeff");
        assertEquals(testCard1.getCardHolderName(), "jeff", "Name not changed");

    }

    @Test
    public void testCardsRead(){
        String cardNumber1 = "40691";
        String cardHolderName1 = "Charles";
        String cardNumber2 = "42689";
        String cardHolderName2 = "Sergio";
        Card testCard1 = new Card(cardNumber1, cardHolderName1);
        Card testCard2 = new Card(cardNumber2, cardHolderName2);
        ArrayList<Card> cardList = new ArrayList<>();
        cardList.add(testCard1);
        cardList.add(testCard2);
        ArrayList<Card> readCardList = testCard1.readCards("resources/test_cards.txt");
        boolean flag = false;
        for(int i=0; i<2; i++) {
            if(((cardList.get(i)).getCardNumber()).equals(((readCardList.get(i)).getCardNumber())) == false) {
                flag = true;
            }
            if(((cardList.get(i)).getCardHolderName()).equals(((readCardList.get(i)).getCardHolderName())) == false) {
                flag = true;
            }
        }
        assertFalse(flag, "Values don't match");
        assertEquals(testCard1.readCards("resources/null.txt"), null, "Read file successfully");
    }

    @Test
    public void cinemaSetterMethods(){
        int c_id = 1;
        String c_name = "Event";
        String location = "Bondi Junction";
        ArrayList<MovieInstance> movies = new ArrayList<MovieInstance>();
        ArrayList<Movie> moviesParent = new ArrayList<Movie>();
        Cinema testCinema = new Cinema(c_id, c_name, location,movies, moviesParent);

        testCinema.setLocation("Fred's House");
        assertEquals(testCinema.getLocation(), "Fred's House", "Incorrect Location");

        ArrayList<MovieInstance> movies2 = new ArrayList<MovieInstance>();
        testCinema.setMovies(movies2);
        assertEquals(testCinema.getMovies(), movies2, "Incorrect movies");
        testCinema.setName("John's House");
        assertEquals(testCinema.getName(), "John's House", "Incorrect Name");

        assertEquals(testCinema.getMovieParents(), moviesParent, "Incorrect parent array");
        assertEquals(testCinema.getId(), c_id, "Incorrect ID");
        }


    @Test
    public void userInput1(){
        //Add movie data
        String input = "John\n" + "Good Movie\n" + "America\n" + "G\n" + "7/11\n" + "11/11/2011\n" + "Jane Doe\n" + "cancel\n";
        // LocalDate.parse("11-11-2001");
        InputStream is = new ByteArrayInputStream(input.getBytes(StandardCharsets.UTF_8));
        UserInput u = new UserInput(is, System.out);

        int newm_id = 2;
        int newm2_id = 3;
        String newName = "Movie";
        String newSynopsis = "Synopsis";
        String newRating = "G";
        String newReleaseDate = "10/10/2010";
        String actor3 = "Leo Di Caprio";
        String actor4 = "Ched";
        ArrayList<String> newCast = new ArrayList<String>();
        newCast.add(actor3);
        newCast.add(actor4);
        Movie newMovie = new Movie(newm_id, newName, newSynopsis, newRating, newReleaseDate, newCast);
        Movie newMovie2 = new Movie(newm2_id, newName, newSynopsis, newRating, newReleaseDate, newCast);
        ArrayList<Movie> movies = new ArrayList<Movie>();
        movies.add(newMovie);
        movies.add(newMovie2);
        u.addMovieData(movies);
    }

    @Test
    public void userCardInit(){
        String input = "resources/test_cards.txt";
        InputStream is = new ByteArrayInputStream(input.getBytes(StandardCharsets.UTF_8));
        UserInput u = new UserInput(is, System.out);
        u.cardInit();
    }
    @Test
    public void testGetUsername(){
        String input = "Jeff";
        InputStream is = new ByteArrayInputStream(input.getBytes(StandardCharsets.UTF_8));
        UserInput u = new UserInput(is, System.out);
        assertEquals(u.getUsername(), input, "Invalid Username");
    }

    @Test
    public void testSaveManagerReport() throws Exception {
        String input = "";
        InputStream is = new ByteArrayInputStream(input.getBytes(StandardCharsets.UTF_8));
        UserInput u = new UserInput(is, System.out);
        u.saveManagerReport("");
        u.saveManagerReport("resources/test_managerreport.txt");
        u.writeError("Bobby brown", "No more popcorn left");
        u.saveManagerReport("resources/test_managerreport.txt");
    }

    @Test
    public void testReadManReport() throws Exception{
        String filename = "resources/test_managerreport.txt";
        UserInput u = new UserInput(System.in, System.out);
        u.writeError("Bobby brown", "No more popcorn left");
        u.getManagerReport();
        u.readManagerReport("bob");
        u.saveManagerReport("resources/test_managerreport.txt");
        u.readManagerReport(filename);
    }

    @Test
    public void testGetPassword(){
        String input = "Jeff";
        InputStream is = new ByteArrayInputStream(input.getBytes(StandardCharsets.UTF_8));
        UserInput u = new UserInput(is, System.out);
        assertEquals(u.getPassword(), input, "Invalid Password");
    }

    @Test
    public void testGetBasePriceInstance(){
        int c_id = 1;
        int m_id = 1;
        String name = "Movie";
        String synopsis = "Synopsis";
        String rating = "G";
        String releaseDate = "10/10/2010";
        String actor1 = "Matt Damon";
        String actor2 = "Maaaaaatt Daaaaaamon";
        ArrayList<String> cast = new ArrayList<String>();
        cast.add(actor1);
        cast.add(actor2);
        Movie testMovie = new Movie(m_id, name, synopsis, rating, releaseDate, cast);
        ArrayList<Movie> moviesParent = new ArrayList<Movie>();
        moviesParent.add(testMovie);

        String c_name = "Event";
        String location = "Bondi Junction";

        int f_seatsOpen = 40;
        int f_seatsCapacity = 50;
        int m_seatsOpen = 40;
        int m_seatsCapacity = 50;
        int r_seatsOpen = 40;
        int r_seatsCapacity = 50;
        String day = "Monday";
        LocalTime time = LocalTime.of(11, 30, 00, 00);
        String screenSize = "Gold";
        BigDecimal basePrice = new BigDecimal("20");
        BigDecimal ticketPrice = new BigDecimal("1.6");

        MovieInstance movInst = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day, time, screenSize, basePrice);
        assertEquals(movInst.getBasePrice(), "20");
    }

    @Test
    public void testGetCIdInstance(){
        int c_id = 1;
        int m_id = 1;
        String name = "Movie";
        String synopsis = "Synopsis";
        String rating = "G";
        String releaseDate = "10/10/2010";
        String actor1 = "Matt Damon";
        String actor2 = "Maaaaaatt Daaaaaamon";
        ArrayList<String> cast = new ArrayList<String>();
        cast.add(actor1);
        cast.add(actor2);
        Movie testMovie = new Movie(m_id, name, synopsis, rating, releaseDate, cast);
        ArrayList<Movie> moviesParent = new ArrayList<Movie>();
        moviesParent.add(testMovie);

        String c_name = "Event";
        String location = "Bondi Junction";

        int f_seatsOpen = 40;
        int f_seatsCapacity = 50;
        int m_seatsOpen = 40;
        int m_seatsCapacity = 50;
        int r_seatsOpen = 40;
        int r_seatsCapacity = 50;
        String day = "Monday";
        LocalTime time = LocalTime.of(11, 30, 00, 00);
        String screenSize = "Gold";
        BigDecimal basePrice = new BigDecimal("20");
        BigDecimal ticketPrice = new BigDecimal("1.6");

        MovieInstance movInst = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day, time, screenSize, basePrice);
        assertEquals(movInst.getC_id(), 1);
    }

    @Test
    public void testGetMIdInstance(){
        int c_id = 1;
        int m_id = 1;
        String name = "Movie";
        String synopsis = "Synopsis";
        String rating = "G";
        String releaseDate = "10/10/2010";
        String actor1 = "Matt Damon";
        String actor2 = "Maaaaaatt Daaaaaamon";
        ArrayList<String> cast = new ArrayList<String>();
        cast.add(actor1);
        cast.add(actor2);
        Movie testMovie = new Movie(m_id, name, synopsis, rating, releaseDate, cast);
        ArrayList<Movie> moviesParent = new ArrayList<Movie>();
        moviesParent.add(testMovie);

        String c_name = "Event";
        String location = "Bondi Junction";

        int f_seatsOpen = 40;
        int f_seatsCapacity = 50;
        int m_seatsOpen = 40;
        int m_seatsCapacity = 50;
        int r_seatsOpen = 40;
        int r_seatsCapacity = 50;
        String day = "Monday";
        LocalTime time = LocalTime.of(11, 30, 00, 00);
        String screenSize = "Gold";
        BigDecimal basePrice = new BigDecimal("20");
        BigDecimal ticketPrice = new BigDecimal("1.6");

        MovieInstance movInst = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day, time, screenSize, basePrice);
        assertEquals(movInst.getM_id(), 1);
    }

    @Test
    public void testGetDayInstance(){
        int c_id = 1;
        int m_id = 1;
        String name = "Movie";
        String synopsis = "Synopsis";
        String rating = "G";
        String releaseDate = "10/10/2010";
        String actor1 = "Matt Damon";
        String actor2 = "Maaaaaatt Daaaaaamon";
        ArrayList<String> cast = new ArrayList<String>();
        cast.add(actor1);
        cast.add(actor2);
        Movie testMovie = new Movie(m_id, name, synopsis, rating, releaseDate, cast);
        ArrayList<Movie> moviesParent = new ArrayList<Movie>();
        moviesParent.add(testMovie);

        String c_name = "Event";
        String location = "Bondi Junction";

        int f_seatsOpen = 40;
        int f_seatsCapacity = 50;
        int m_seatsOpen = 40;
        int m_seatsCapacity = 50;
        int r_seatsOpen = 40;
        int r_seatsCapacity = 50;
        String day = "Monday";
        LocalTime time = LocalTime.of(11, 30, 00, 00);
        String screenSize = "Gold";
        BigDecimal basePrice = new BigDecimal("20");
        BigDecimal ticketPrice = new BigDecimal("1.6");

        MovieInstance movInst = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day, time, screenSize, basePrice);
        assertEquals(movInst.getDay(), "Monday");
    }

    @Test
    public void testGetFCapacityInstance(){
        int c_id = 1;
        int m_id = 1;
        String name = "Movie";
        String synopsis = "Synopsis";
        String rating = "G";
        String releaseDate = "10/10/2010";
        String actor1 = "Matt Damon";
        String actor2 = "Maaaaaatt Daaaaaamon";
        ArrayList<String> cast = new ArrayList<String>();
        cast.add(actor1);
        cast.add(actor2);
        Movie testMovie = new Movie(m_id, name, synopsis, rating, releaseDate, cast);
        ArrayList<Movie> moviesParent = new ArrayList<Movie>();
        moviesParent.add(testMovie);

        String c_name = "Event";
        String location = "Bondi Junction";

        int f_seatsOpen = 40;
        int f_seatsCapacity = 50;
        int m_seatsOpen = 40;
        int m_seatsCapacity = 50;
        int r_seatsOpen = 40;
        int r_seatsCapacity = 50;
        String day = "Monday";
        LocalTime time = LocalTime.of(11, 30, 00, 00);
        String screenSize = "Gold";
        BigDecimal basePrice = new BigDecimal("20");
        BigDecimal ticketPrice = new BigDecimal("1.6");

        MovieInstance movInst = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day, time, screenSize, basePrice);
        assertEquals(movInst.getF_seatsCapacity(), 50);
    }

    @Test
    public void testGetFOpenInstance(){
        int c_id = 1;
        int m_id = 1;
        String name = "Movie";
        String synopsis = "Synopsis";
        String rating = "G";
        String releaseDate = "10/10/2010";
        String actor1 = "Matt Damon";
        String actor2 = "Maaaaaatt Daaaaaamon";
        ArrayList<String> cast = new ArrayList<String>();
        cast.add(actor1);
        cast.add(actor2);
        Movie testMovie = new Movie(m_id, name, synopsis, rating, releaseDate, cast);
        ArrayList<Movie> moviesParent = new ArrayList<Movie>();
        moviesParent.add(testMovie);

        String c_name = "Event";
        String location = "Bondi Junction";

        int f_seatsOpen = 40;
        int f_seatsCapacity = 50;
        int m_seatsOpen = 40;
        int m_seatsCapacity = 50;
        int r_seatsOpen = 40;
        int r_seatsCapacity = 50;
        String day = "Monday";
        LocalTime time = LocalTime.of(11, 30, 00, 00);
        String screenSize = "Gold";
        BigDecimal basePrice = new BigDecimal("20");
        BigDecimal ticketPrice = new BigDecimal("1.6");

        MovieInstance movInst = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day, time, screenSize, basePrice);
        assertEquals(movInst.getF_seatsOpen(), 50);
    }

    @Test
    public void testGetMCapacityInstance(){
        int c_id = 1;
        int m_id = 1;
        String name = "Movie";
        String synopsis = "Synopsis";
        String rating = "G";
        String releaseDate = "10/10/2010";
        String actor1 = "Matt Damon";
        String actor2 = "Maaaaaatt Daaaaaamon";
        ArrayList<String> cast = new ArrayList<String>();
        cast.add(actor1);
        cast.add(actor2);
        Movie testMovie = new Movie(m_id, name, synopsis, rating, releaseDate, cast);
        ArrayList<Movie> moviesParent = new ArrayList<Movie>();
        moviesParent.add(testMovie);

        String c_name = "Event";
        String location = "Bondi Junction";

        int f_seatsOpen = 40;
        int f_seatsCapacity = 50;
        int m_seatsOpen = 40;
        int m_seatsCapacity = 50;
        int r_seatsOpen = 40;
        int r_seatsCapacity = 50;
        String day = "Monday";
        LocalTime time = LocalTime.of(11, 30, 00, 00);
        String screenSize = "Gold";
        BigDecimal basePrice = new BigDecimal("20");
        BigDecimal ticketPrice = new BigDecimal("1.6");

        MovieInstance movInst = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day, time, screenSize, basePrice);
        assertEquals(movInst.getM_seatsCapacity(), 50);
    }

    @Test
    public void testGetMOpenInstance(){
        int c_id = 1;
        int m_id = 1;
        String name = "Movie";
        String synopsis = "Synopsis";
        String rating = "G";
        String releaseDate = "10/10/2010";
        String actor1 = "Matt Damon";
        String actor2 = "Maaaaaatt Daaaaaamon";
        ArrayList<String> cast = new ArrayList<String>();
        cast.add(actor1);
        cast.add(actor2);
        Movie testMovie = new Movie(m_id, name, synopsis, rating, releaseDate, cast);
        ArrayList<Movie> moviesParent = new ArrayList<Movie>();
        moviesParent.add(testMovie);

        String c_name = "Event";
        String location = "Bondi Junction";

        int f_seatsOpen = 40;
        int f_seatsCapacity = 50;
        int m_seatsOpen = 40;
        int m_seatsCapacity = 50;
        int r_seatsOpen = 40;
        int r_seatsCapacity = 50;
        String day = "Monday";
        LocalTime time = LocalTime.of(11, 30, 00, 00);
        String screenSize = "Gold";
        BigDecimal basePrice = new BigDecimal("20");
        BigDecimal ticketPrice = new BigDecimal("1.6");

        MovieInstance movInst = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day, time, screenSize, basePrice);
        assertEquals(movInst.getM_seatsOpen(), 50);
    }

    @Test
    public void testGetRCapacityInstance(){
        int c_id = 1;
        int m_id = 1;
        String name = "Movie";
        String synopsis = "Synopsis";
        String rating = "G";
        String releaseDate = "10/10/2010";
        String actor1 = "Matt Damon";
        String actor2 = "Maaaaaatt Daaaaaamon";
        ArrayList<String> cast = new ArrayList<String>();
        cast.add(actor1);
        cast.add(actor2);
        Movie testMovie = new Movie(m_id, name, synopsis, rating, releaseDate, cast);
        ArrayList<Movie> moviesParent = new ArrayList<Movie>();
        moviesParent.add(testMovie);

        String c_name = "Event";
        String location = "Bondi Junction";

        int f_seatsOpen = 40;
        int f_seatsCapacity = 50;
        int m_seatsOpen = 40;
        int m_seatsCapacity = 50;
        int r_seatsOpen = 40;
        int r_seatsCapacity = 50;
        String day = "Monday";
        LocalTime time = LocalTime.of(11, 30, 00, 00);
        String screenSize = "Gold";
        BigDecimal basePrice = new BigDecimal("20");
        BigDecimal ticketPrice = new BigDecimal("1.6");

        MovieInstance movInst = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day, time, screenSize, basePrice);
        assertEquals(movInst.getR_seatsCapacity(), 50);
    }

    @Test
    public void testGetROpenInstance(){
        int c_id = 1;
        int m_id = 1;
        String name = "Movie";
        String synopsis = "Synopsis";
        String rating = "G";
        String releaseDate = "10/10/2010";
        String actor1 = "Matt Damon";
        String actor2 = "Maaaaaatt Daaaaaamon";
        ArrayList<String> cast = new ArrayList<String>();
        cast.add(actor1);
        cast.add(actor2);
        Movie testMovie = new Movie(m_id, name, synopsis, rating, releaseDate, cast);
        ArrayList<Movie> moviesParent = new ArrayList<Movie>();
        moviesParent.add(testMovie);

        String c_name = "Event";
        String location = "Bondi Junction";

        int f_seatsOpen = 40;
        int f_seatsCapacity = 50;
        int m_seatsOpen = 40;
        int m_seatsCapacity = 50;
        int r_seatsOpen = 40;
        int r_seatsCapacity = 50;
        String day = "Monday";
        LocalTime time = LocalTime.of(11, 30, 00, 00);
        String screenSize = "Gold";
        BigDecimal basePrice = new BigDecimal("20");
        BigDecimal ticketPrice = new BigDecimal("1.6");

        MovieInstance movInst = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day, time, screenSize, basePrice);
        assertEquals(movInst.getR_seatsOpen(), 50);
    }

    @Test
    public void testGetNameInstance(){
        int c_id = 1;
        int m_id = 1;
        String name = "Movie";
        String synopsis = "Synopsis";
        String rating = "G";
        String releaseDate = "10/10/2010";
        String actor1 = "Matt Damon";
        String actor2 = "Maaaaaatt Daaaaaamon";
        ArrayList<String> cast = new ArrayList<String>();
        cast.add(actor1);
        cast.add(actor2);
        Movie testMovie = new Movie(m_id, name, synopsis, rating, releaseDate, cast);
        ArrayList<Movie> moviesParent = new ArrayList<Movie>();
        moviesParent.add(testMovie);

        String c_name = "Event";
        String location = "Bondi Junction";

        int f_seatsOpen = 40;
        int f_seatsCapacity = 50;
        int m_seatsOpen = 40;
        int m_seatsCapacity = 50;
        int r_seatsOpen = 40;
        int r_seatsCapacity = 50;
        String day = "Monday";
        LocalTime time = LocalTime.of(11, 30, 00, 00);
        String screenSize = "Gold";
        BigDecimal basePrice = new BigDecimal("20");
        BigDecimal ticketPrice = new BigDecimal("1.6");

        MovieInstance movInst = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day, time, screenSize, basePrice);
        assertEquals(movInst.getName(), "Movie");
    }

    @Test
    public void testGetScreenSizeInstance(){
        int c_id = 1;
        int m_id = 1;
        String name = "Movie";
        String synopsis = "Synopsis";
        String rating = "G";
        String releaseDate = "10/10/2010";
        String actor1 = "Matt Damon";
        String actor2 = "Maaaaaatt Daaaaaamon";
        ArrayList<String> cast = new ArrayList<String>();
        cast.add(actor1);
        cast.add(actor2);
        Movie testMovie = new Movie(m_id, name, synopsis, rating, releaseDate, cast);
        ArrayList<Movie> moviesParent = new ArrayList<Movie>();
        moviesParent.add(testMovie);

        String c_name = "Event";
        String location = "Bondi Junction";

        int f_seatsOpen = 40;
        int f_seatsCapacity = 50;
        int m_seatsOpen = 40;
        int m_seatsCapacity = 50;
        int r_seatsOpen = 40;
        int r_seatsCapacity = 50;
        String day = "Monday";
        LocalTime time = LocalTime.of(11, 30, 00, 00);
        String screenSize = "Gold";
        BigDecimal basePrice = new BigDecimal("20");
        BigDecimal ticketPrice = new BigDecimal("1.6");

        MovieInstance movInst = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day, time, screenSize, basePrice);
        assertEquals(movInst.getScreenSize(), "Gold");
    }

    @Test
    public void testGetTimeInstance(){
        int c_id = 1;
        int m_id = 1;
        String name = "Movie";
        String synopsis = "Synopsis";
        String rating = "G";
        String releaseDate = "10/10/2010";
        String actor1 = "Matt Damon";
        String actor2 = "Maaaaaatt Daaaaaamon";
        ArrayList<String> cast = new ArrayList<String>();
        cast.add(actor1);
        cast.add(actor2);
        Movie testMovie = new Movie(m_id, name, synopsis, rating, releaseDate, cast);
        ArrayList<Movie> moviesParent = new ArrayList<Movie>();
        moviesParent.add(testMovie);

        String c_name = "Event";
        String location = "Bondi Junction";

        int f_seatsOpen = 40;
        int f_seatsCapacity = 50;
        int m_seatsOpen = 40;
        int m_seatsCapacity = 50;
        int r_seatsOpen = 40;
        int r_seatsCapacity = 50;
        String day = "Monday";
        LocalTime time = LocalTime.of(11, 30, 00, 00);
        String screenSize = "Gold";
        BigDecimal basePrice = new BigDecimal("20");
        BigDecimal ticketPrice = new BigDecimal("1.6");

        MovieInstance movInst = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day, time, screenSize, basePrice);
        LocalTime time2 = LocalTime.parse("11:30:00");
        assertEquals(0, movInst.getTime().compareTo(time2));
    }

    @Test
    public void testSetDayInstance(){
        int c_id = 1;
        int m_id = 1;
        String name = "Movie";
        String synopsis = "Synopsis";
        String rating = "G";
        String releaseDate = "10/10/2010";
        String actor1 = "Matt Damon";
        String actor2 = "Maaaaaatt Daaaaaamon";
        ArrayList<String> cast = new ArrayList<String>();
        cast.add(actor1);
        cast.add(actor2);
        Movie testMovie = new Movie(m_id, name, synopsis, rating, releaseDate, cast);
        ArrayList<Movie> moviesParent = new ArrayList<Movie>();
        moviesParent.add(testMovie);

        String c_name = "Event";
        String location = "Bondi Junction";

        int f_seatsOpen = 40;
        int f_seatsCapacity = 50;
        int m_seatsOpen = 40;
        int m_seatsCapacity = 50;
        int r_seatsOpen = 40;
        int r_seatsCapacity = 50;
        String day = "Monday";
        LocalTime time = LocalTime.of(11, 30, 00, 00);
        String screenSize = "Gold";
        BigDecimal basePrice = new BigDecimal("20");
        BigDecimal ticketPrice = new BigDecimal("1.6");

        MovieInstance movInst = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day, time, screenSize, basePrice);
        movInst.setDay("Tuesday");
        assertEquals(movInst.getDay(), "Tuesday");
        movInst.setDay("Not a real day");
        assertEquals(movInst.getDay(), "Tuesday");
    }

    @Test
    public void testSetFOpenInstance(){
        int c_id = 1;
        int m_id = 1;
        String name = "Movie";
        String synopsis = "Synopsis";
        String rating = "G";
        String releaseDate = "10/10/2010";
        String actor1 = "Matt Damon";
        String actor2 = "Maaaaaatt Daaaaaamon";
        ArrayList<String> cast = new ArrayList<String>();
        cast.add(actor1);
        cast.add(actor2);
        Movie testMovie = new Movie(m_id, name, synopsis, rating, releaseDate, cast);
        ArrayList<Movie> moviesParent = new ArrayList<Movie>();
        moviesParent.add(testMovie);

        String c_name = "Event";
        String location = "Bondi Junction";

        int f_seatsOpen = 40;
        int f_seatsCapacity = 50;
        int m_seatsOpen = 40;
        int m_seatsCapacity = 50;
        int r_seatsOpen = 40;
        int r_seatsCapacity = 50;
        String day = "Monday";
        LocalTime time = LocalTime.of(11, 30, 00, 00);
        String screenSize = "Gold";
        BigDecimal basePrice = new BigDecimal("20");
        BigDecimal ticketPrice = new BigDecimal("1.6");

        MovieInstance movInst = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day, time, screenSize, basePrice);
        movInst.setF_seatsOpen(30);
        assertEquals(movInst.getF_seatsOpen(), 30);
        movInst.setF_seatsOpen(1000);
        assertEquals(movInst.getF_seatsOpen(), 30);
    }

    @Test
    public void testSetROpenInstance(){
        int c_id = 1;
        int m_id = 1;
        String name = "Movie";
        String synopsis = "Synopsis";
        String rating = "G";
        String releaseDate = "10/10/2010";
        String actor1 = "Matt Damon";
        String actor2 = "Maaaaaatt Daaaaaamon";
        ArrayList<String> cast = new ArrayList<String>();
        cast.add(actor1);
        cast.add(actor2);
        Movie testMovie = new Movie(m_id, name, synopsis, rating, releaseDate, cast);
        ArrayList<Movie> moviesParent = new ArrayList<Movie>();
        moviesParent.add(testMovie);

        String c_name = "Event";
        String location = "Bondi Junction";

        int f_seatsOpen = 40;
        int f_seatsCapacity = 50;
        int m_seatsOpen = 40;
        int m_seatsCapacity = 50;
        int r_seatsOpen = 40;
        int r_seatsCapacity = 50;
        String day = "Monday";
        LocalTime time = LocalTime.of(11, 30, 00, 00);
        String screenSize = "Gold";
        BigDecimal basePrice = new BigDecimal("20");
        BigDecimal ticketPrice = new BigDecimal("1.6");

        MovieInstance movInst = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day, time, screenSize, basePrice);
        movInst.setR_seatsOpen(30);
        assertEquals(movInst.getR_seatsOpen(), 30);
        movInst.setR_seatsOpen(1000);
        assertEquals(movInst.getR_seatsOpen(), 30);
    }

    @Test
    public void testSetMOpenInstance(){
        int c_id = 1;
        int m_id = 1;
        String name = "Movie";
        String synopsis = "Synopsis";
        String rating = "G";
        String releaseDate = "10/10/2010";
        String actor1 = "Matt Damon";
        String actor2 = "Maaaaaatt Daaaaaamon";
        ArrayList<String> cast = new ArrayList<String>();
        cast.add(actor1);
        cast.add(actor2);
        Movie testMovie = new Movie(m_id, name, synopsis, rating, releaseDate, cast);
        ArrayList<Movie> moviesParent = new ArrayList<Movie>();
        moviesParent.add(testMovie);

        String c_name = "Event";
        String location = "Bondi Junction";

        int f_seatsOpen = 40;
        int f_seatsCapacity = 50;
        int m_seatsOpen = 40;
        int m_seatsCapacity = 50;
        int r_seatsOpen = 40;
        int r_seatsCapacity = 50;
        String day = "Monday";
        LocalTime time = LocalTime.of(11, 30, 00, 00);
        String screenSize = "Gold";
        BigDecimal basePrice = new BigDecimal("20");
        BigDecimal ticketPrice = new BigDecimal("1.6");

        MovieInstance movInst = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day, time, screenSize, basePrice);
        movInst.setM_seatsOpen(30);
        assertEquals(movInst.getM_seatsOpen(), 30);
        movInst.setM_seatsOpen(1000);
        assertEquals(movInst.getM_seatsOpen(), 30);
    }

    @Test
    public void testSetScreenSizeInstance(){
        int c_id = 1;
        int m_id = 1;
        String name = "Movie";
        String synopsis = "Synopsis";
        String rating = "G";
        String releaseDate = "10/10/2010";
        String actor1 = "Matt Damon";
        String actor2 = "Maaaaaatt Daaaaaamon";
        ArrayList<String> cast = new ArrayList<String>();
        cast.add(actor1);
        cast.add(actor2);
        Movie testMovie = new Movie(m_id, name, synopsis, rating, releaseDate, cast);
        ArrayList<Movie> moviesParent = new ArrayList<Movie>();
        moviesParent.add(testMovie);

        String c_name = "Event";
        String location = "Bondi Junction";

        int f_seatsOpen = 40;
        int f_seatsCapacity = 50;
        int m_seatsOpen = 40;
        int m_seatsCapacity = 50;
        int r_seatsOpen = 40;
        int r_seatsCapacity = 50;
        String day = "Monday";
        LocalTime time = LocalTime.of(11, 30, 00, 00);
        String screenSize = "Gold";
        BigDecimal basePrice = new BigDecimal("20");
        BigDecimal ticketPrice = new BigDecimal("1.6");

        MovieInstance movInst = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day, time, screenSize, basePrice);
        movInst.setScreenSize("Bronze");
        assertEquals(movInst.getScreenSize(), "Bronze");
    }

    @Test
    public void testSetFCapacityInstance(){
        int c_id = 1;
        int m_id = 1;
        String name = "Movie";
        String synopsis = "Synopsis";
        String rating = "G";
        String releaseDate = "10/10/2010";
        String actor1 = "Matt Damon";
        String actor2 = "Maaaaaatt Daaaaaamon";
        ArrayList<String> cast = new ArrayList<String>();
        cast.add(actor1);
        cast.add(actor2);
        Movie testMovie = new Movie(m_id, name, synopsis, rating, releaseDate, cast);
        ArrayList<Movie> moviesParent = new ArrayList<Movie>();
        moviesParent.add(testMovie);

        String c_name = "Event";
        String location = "Bondi Junction";

        int f_seatsOpen = 40;
        int f_seatsCapacity = 50;
        int m_seatsOpen = 40;
        int m_seatsCapacity = 50;
        int r_seatsOpen = 40;
        int r_seatsCapacity = 50;
        String day = "Monday";
        LocalTime time = LocalTime.of(11, 30, 00, 00);
        String screenSize = "Gold";
        BigDecimal basePrice = new BigDecimal("20");
        BigDecimal ticketPrice = new BigDecimal("1.6");

        MovieInstance movInst = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day, time, screenSize, basePrice);
        movInst.setF_seatsCapacity(100);
        assertEquals(movInst.getF_seatsCapacity(), 100);
        movInst.setF_seatsCapacity(-100);
        assertEquals(movInst.getF_seatsCapacity(), 100);
    }

    @Test
    public void testSetMCapacityInstance(){
        int c_id = 1;
        int m_id = 1;
        String name = "Movie";
        String synopsis = "Synopsis";
        String rating = "G";
        String releaseDate = "10/10/2010";
        String actor1 = "Matt Damon";
        String actor2 = "Maaaaaatt Daaaaaamon";
        ArrayList<String> cast = new ArrayList<String>();
        cast.add(actor1);
        cast.add(actor2);
        Movie testMovie = new Movie(m_id, name, synopsis, rating, releaseDate, cast);
        ArrayList<Movie> moviesParent = new ArrayList<Movie>();
        moviesParent.add(testMovie);

        String c_name = "Event";
        String location = "Bondi Junction";

        int f_seatsOpen = 40;
        int f_seatsCapacity = 50;
        int m_seatsOpen = 40;
        int m_seatsCapacity = 50;
        int r_seatsOpen = 40;
        int r_seatsCapacity = 50;
        String day = "Monday";
        LocalTime time = LocalTime.of(11, 30, 00, 00);
        String screenSize = "Gold";
        BigDecimal basePrice = new BigDecimal("20");
        BigDecimal ticketPrice = new BigDecimal("1.6");

        MovieInstance movInst = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day, time, screenSize, basePrice);
        movInst.setM_seatsCapacity(100);
        assertEquals(movInst.getM_seatsCapacity(), 100);
        movInst.setM_seatsCapacity(-100);
        assertEquals(movInst.getM_seatsCapacity(), 100);
    }

    @Test
    public void testSetRCapacityInstance(){
        int c_id = 1;
        int m_id = 1;
        String name = "Movie";
        String synopsis = "Synopsis";
        String rating = "G";
        String releaseDate = "10/10/2010";
        String actor1 = "Matt Damon";
        String actor2 = "Maaaaaatt Daaaaaamon";
        ArrayList<String> cast = new ArrayList<String>();
        cast.add(actor1);
        cast.add(actor2);
        Movie testMovie = new Movie(m_id, name, synopsis, rating, releaseDate, cast);
        ArrayList<Movie> moviesParent = new ArrayList<Movie>();
        moviesParent.add(testMovie);

        String c_name = "Event";
        String location = "Bondi Junction";

        int f_seatsOpen = 40;
        int f_seatsCapacity = 50;
        int m_seatsOpen = 40;
        int m_seatsCapacity = 50;
        int r_seatsOpen = 40;
        int r_seatsCapacity = 50;
        String day = "Monday";
        LocalTime time = LocalTime.of(11, 30, 00, 00);
        String screenSize = "Gold";
        BigDecimal basePrice = new BigDecimal("20");
        BigDecimal ticketPrice = new BigDecimal("1.6");

        MovieInstance movInst = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day, time, screenSize, basePrice);
        movInst.setR_seatsCapacity(100);
        assertEquals(movInst.getR_seatsCapacity(), 100);
        movInst.setR_seatsCapacity(-100);
        assertEquals(movInst.getR_seatsCapacity(), 100);
    }

    @Test
    public void testUpdateSeatsOpenInstance(){
        int c_id = 1;
        int m_id = 1;
        String name = "Movie";
        String synopsis = "Synopsis";
        String rating = "G";
        String releaseDate = "10/10/2010";
        String actor1 = "Matt Damon";
        String actor2 = "Maaaaaatt Daaaaaamon";
        ArrayList<String> cast = new ArrayList<String>();
        cast.add(actor1);
        cast.add(actor2);
        Movie testMovie = new Movie(m_id, name, synopsis, rating, releaseDate, cast);
        ArrayList<Movie> moviesParent = new ArrayList<Movie>();
        moviesParent.add(testMovie);

        String c_name = "Event";
        String location = "Bondi Junction";

        int f_seatsOpen = 40;
        int f_seatsCapacity = 50;
        int m_seatsOpen = 40;
        int m_seatsCapacity = 50;
        int r_seatsOpen = 40;
        int r_seatsCapacity = 50;
        String day = "Monday";
        LocalTime time = LocalTime.of(11, 30, 00, 00);
        String screenSize = "Gold";
        BigDecimal basePrice = new BigDecimal("20");
        BigDecimal ticketPrice = new BigDecimal("1.6");

        MovieInstance movInst = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day, time, screenSize, basePrice);
        movInst.updateSeatsOpen(15,25,35);
        assertEquals(movInst.getF_seatsOpen(), 35);
        assertEquals(movInst.getM_seatsOpen(), 25);
        assertEquals(movInst.getR_seatsOpen(), 15);
    }

    @Test
    public void testGetTicketPriceInstance(){
        int c_id = 1;
        int m_id = 1;
        String name = "Movie";
        String synopsis = "Synopsis";
        String rating = "G";
        String releaseDate = "10/10/2010";
        String actor1 = "Matt Damon";
        String actor2 = "Maaaaaatt Daaaaaamon";
        ArrayList<String> cast = new ArrayList<String>();
        cast.add(actor1);
        cast.add(actor2);
        Movie testMovie = new Movie(m_id, name, synopsis, rating, releaseDate, cast);
        ArrayList<Movie> moviesParent = new ArrayList<Movie>();
        moviesParent.add(testMovie);

        String c_name = "Event";
        String location = "Bondi Junction";

        int f_seatsOpen = 40;
        int f_seatsCapacity = 50;
        int m_seatsOpen = 40;
        int m_seatsCapacity = 50;
        int r_seatsOpen = 40;
        int r_seatsCapacity = 50;
        String day = "Monday";
        LocalTime time = LocalTime.of(11, 30, 00, 00);
        String screenSize = "Gold";
        BigDecimal basePrice = new BigDecimal("20");

        MovieInstance movInst = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day, time, screenSize, basePrice);
        assertEquals(0, movInst.getTicketPrice().compareTo(new BigDecimal("32")));
        movInst.setScreenSize("silver");
        assertEquals(0, movInst.getTicketPrice().compareTo(new BigDecimal("24")));
        movInst.setScreenSize("bronze");
        assertEquals(0, movInst.getTicketPrice().compareTo(new BigDecimal("16")));
        movInst.setScreenSize("invalid!");
        assertEquals(0, movInst.getTicketPrice().compareTo(new BigDecimal("0")));
    }

    @Test
    public void cinemaTestSort() {
        int c_id = 1;
        int m_id = 1;
        String name = "Movie";
        String synopsis = "Synopsis";
        String rating = "G";
        String releaseDate = "10/10/2010";
        String actor1 = "Matt Damon";
        String actor2 = "Maaaaaatt Daaaaaamon";
        ArrayList<String> cast = new ArrayList<String>();
        cast.add(actor1);
        cast.add(actor2);
        Movie testMovie = new Movie(m_id, name, synopsis, rating, releaseDate, cast);
        ArrayList<Movie> moviesParent = new ArrayList<Movie>();
        moviesParent.add(testMovie);

        String c_name = "Event";
        String location = "Bondi Junction";

        int f_seatsCapacity = 50;
        int m_seatsCapacity = 50;
        int r_seatsCapacity = 50;
        String day = "Monday";
        String day2 = "Friday";
        LocalTime time = LocalTime.of(12, 00, 00, 00);
        LocalTime time2 = LocalTime.of(10, 00, 00, 00);
        String screenSize = "Gold";
        BigDecimal basePrice = new BigDecimal("20");

        MovieInstance movInst = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day, time, screenSize, basePrice);
        MovieInstance movInst2 = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day, time2, screenSize, basePrice);
        MovieInstance movInst3 = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day2, time, screenSize, basePrice);

        ArrayList<MovieInstance> movies = new ArrayList<>();
        movies.add(movInst3);
        movies.add(movInst2);
        movies.add(movInst);

        String username = "username";
        String password = "password";

        String cardNumber1 = "40691";
        String cardHolderName1 = "username";
        String cardNumber2 = "42689";
        String cardHolderName2 = "Sergio";
        Card testCard1 = new Card(cardNumber1, cardHolderName1);
        Card testCard2 = new Card(cardNumber2, cardHolderName2);
        ArrayList<Card> testCards = new ArrayList<Card>();
        ArrayList<GiftCard> validGiftCards = new ArrayList<GiftCard>();
        testCards.add(testCard1);
        testCards.add(testCard2);
        String testTicket1 = "Ticket1";
        String testTicket2 = "Ticket2";
        ArrayList<String> testTickets = new ArrayList<String>();
        testTickets.add(testTicket1);
        testTickets.add(testTicket2);

        Cinema testCinema = new Cinema(c_id, c_name, location, movies, moviesParent);

        testCinema.sort();

        assertEquals(testCinema.getMovies().get(0), movInst2);
        assertEquals(testCinema.getMovies().get(1), movInst);
        assertEquals(testCinema.getMovies().get(2), movInst3);
    }

    @Test
    public void cinemaTestSave() {
        int c_id = 1;
        int m_id = 1;
        String name = "Movie";
        String synopsis = "Synopsis";
        String rating = "G";
        String releaseDate = "10/10/2010";
        String actor1 = "Matt Damon";
        String actor2 = "Maaaaaatt Daaaaaamon";
        ArrayList<String> cast = new ArrayList<String>();
        cast.add(actor1);
        cast.add(actor2);
        Movie testMovie = new Movie(m_id, name, synopsis, rating, releaseDate, cast);
        ArrayList<Movie> moviesParent = new ArrayList<Movie>();
        moviesParent.add(testMovie);

        String c_name = "Event";
        String location = "Bondi Junction";

        int f_seatsCapacity = 50;
        int m_seatsCapacity = 50;
        int r_seatsCapacity = 50;
        String day = "Monday";
        String day2 = "Friday";
        LocalTime time = LocalTime.of(12, 00, 00, 00);
        LocalTime time2 = LocalTime.of(10, 00, 00, 00);
        String screenSize = "Gold";
        BigDecimal basePrice = new BigDecimal("20");

        MovieInstance movInst = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day, time, screenSize, basePrice);
        MovieInstance movInst2 = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day, time2, screenSize, basePrice);
        MovieInstance movInst3 = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day2, time, screenSize, basePrice);

        ArrayList<MovieInstance> movies = new ArrayList<>();
        movies.add(movInst3);
        movies.add(movInst2);
        movies.add(movInst);

        String username = "username";
        String password = "password";

        String cardNumber1 = "40691";
        String cardHolderName1 = "username";
        String cardNumber2 = "42689";
        String cardHolderName2 = "Sergio";
        Card testCard1 = new Card(cardNumber1, cardHolderName1);
        Card testCard2 = new Card(cardNumber2, cardHolderName2);
        ArrayList<Card> testCards = new ArrayList<Card>();
        ArrayList<GiftCard> validGiftCards = new ArrayList<GiftCard>();
        testCards.add(testCard1);
        testCards.add(testCard2);
        String testTicket1 = "Ticket1";
        String testTicket2 = "Ticket2";
        ArrayList<String> testTickets = new ArrayList<String>();
        testTickets.add(testTicket1);
        testTickets.add(testTicket2);

        Cinema testCinema = new Cinema(c_id, c_name, location, movies, moviesParent);
        ArrayList<Cinema> cinemas = new ArrayList<>();
        cinemas.add(testCinema);

        ArrayList<Cinema> empty = new ArrayList<>();

        Cinema.saveCinemas("resources/test_cinemas", cinemas);
        Cinema.saveCinemas("resources/test_cinemas.txt", cinemas);
        Cinema.saveCinemas("resources/test_cinemas.txt", empty);
    }

    @Test
    public void cinemaTestRead() {
        int c_id = 1;
        int m_id = 1;
        String name = "Movie";
        String synopsis = "Synopsis";
        String rating = "G";
        String releaseDate = "10/10/2010";
        String actor1 = "Matt Damon";
        String actor2 = "Maaaaaatt Daaaaaamon";
        ArrayList<String> cast = new ArrayList<String>();
        cast.add(actor1);
        cast.add(actor2);
        Movie testMovie = new Movie(m_id, name, synopsis, rating, releaseDate, cast);
        ArrayList<Movie> moviesParent = new ArrayList<Movie>();
        moviesParent.add(testMovie);

        String c_name = "Event";
        String location = "Bondi Junction";

        int f_seatsCapacity = 50;
        int m_seatsCapacity = 50;
        int r_seatsCapacity = 50;
        String day = "Monday";
        String day2 = "Friday";
        LocalTime time = LocalTime.of(12, 00, 00, 00);
        LocalTime time2 = LocalTime.of(10, 00, 00, 00);
        String screenSize = "Gold";
        BigDecimal basePrice = new BigDecimal("20");

        MovieInstance movInst = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day, time, screenSize, basePrice);
        MovieInstance movInst2 = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day, time2, screenSize, basePrice);
        MovieInstance movInst3 = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day2, time, screenSize, basePrice);

        ArrayList<MovieInstance> movies = new ArrayList<>();
        movies.add(movInst3);
        movies.add(movInst2);
        movies.add(movInst);

        String username = "username";
        String password = "password";

        String cardNumber1 = "40691";
        String cardHolderName1 = "username";
        String cardNumber2 = "42689";
        String cardHolderName2 = "Sergio";
        Card testCard1 = new Card(cardNumber1, cardHolderName1);
        Card testCard2 = new Card(cardNumber2, cardHolderName2);
        ArrayList<Card> testCards = new ArrayList<Card>();
        ArrayList<GiftCard> validGiftCards = new ArrayList<GiftCard>();
        testCards.add(testCard1);
        testCards.add(testCard2);
        String testTicket1 = "Ticket1";
        String testTicket2 = "Ticket2";
        ArrayList<String> testTickets = new ArrayList<String>();
        testTickets.add(testTicket1);
        testTickets.add(testTicket2);

        Cinema testCinema = new Cinema(c_id, c_name, location, movies, moviesParent);
        ArrayList<Movie> empty = new ArrayList<>();
        Cinema.readCinemas("resources/test_cinemas", moviesParent);
        Cinema.readCinemas("resources/test_cinemas.txt", moviesParent);
        Cinema.readCinemas("resources/test_cinemas.txt", empty);
    }

    @Test
    public void cinemaTestGetSchedule() {
        int c_id = 1;
        int m_id = 1;
        String name = "Movie";
        String synopsis = "Synopsis";
        String rating = "G";
        String releaseDate = "10/10/2010";
        String actor1 = "Matt Damon";
        String actor2 = "Maaaaaatt Daaaaaamon";
        ArrayList<String> cast = new ArrayList<String>();
        cast.add(actor1);
        cast.add(actor2);
        Movie testMovie = new Movie(m_id, name, synopsis, rating, releaseDate, cast);
        ArrayList<Movie> moviesParent = new ArrayList<Movie>();
        moviesParent.add(testMovie);

        String c_name = "Event";
        String location = "Bondi Junction";

        int f_seatsCapacity = 50;
        int m_seatsCapacity = 50;
        int r_seatsCapacity = 50;
        String day = "Monday";
        String day2 = "Friday";
        LocalTime time = LocalTime.of(12, 00, 00, 00);
        LocalTime time2 = LocalTime.of(10, 00, 00, 00);
        String screenSize = "Gold";
        BigDecimal basePrice = new BigDecimal("20");

        MovieInstance movInst = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day, time, screenSize, basePrice);

        ArrayList<MovieInstance> movies = new ArrayList<>();
        movies.add(movInst);

        String username = "username";
        String password = "password";

        String cardNumber1 = "40691";
        String cardHolderName1 = "username";
        String cardNumber2 = "42689";
        String cardHolderName2 = "Sergio";
        Card testCard1 = new Card(cardNumber1, cardHolderName1);
        Card testCard2 = new Card(cardNumber2, cardHolderName2);
        ArrayList<Card> testCards = new ArrayList<Card>();
        ArrayList<GiftCard> validGiftCards = new ArrayList<GiftCard>();
        testCards.add(testCard1);
        testCards.add(testCard2);
        String testTicket1 = "Ticket1";
        String testTicket2 = "Ticket2";
        ArrayList<String> testTickets = new ArrayList<String>();
        testTickets.add(testTicket1);
        testTickets.add(testTicket2);

        Cinema testCinema = new Cinema(c_id, c_name, location, movies, moviesParent);

        assertEquals(testCinema.getSchedule(), movInst.getName() + ": " + movInst.getSchedule());
    }

    @Test
    public void customerTestSave() {
        String testTicket1 = "Ticket1";
        String testTicket2 = "Ticket2";
        ArrayList<String> testTickets = new ArrayList<String>();
        testTickets.add(testTicket1);
        testTickets.add(testTicket2);
        String cardNumber1 = "40691";
        String cardHolderName1 = "Charles";
        String cardNumber2 = "42689";
        String cardHolderName2 = "Sergio";
        Card testCard1 = new Card(cardNumber1, cardHolderName1);
        Card testCard2 = new Card(cardNumber2, cardHolderName2);
        ArrayList<Card> cards = new ArrayList<>();
        cards.add(testCard1);
        cards.add(testCard2);
        ArrayList<Customer> customers = new ArrayList<>();
        Customer g = new Customer("Broskin", "YOYO", cards,testTickets);
        customers.add(g);
        ArrayList<Customer> empty = new ArrayList<>();
        Customer.saveCustomers("resources/test_customers", customers);
        Customer.saveCustomers("resources/test_customers.txt", customers);
        Customer.saveCustomers("resources/test_customers.txt", empty);
    }

    @Test
    public void customerTestRead() {
        String cardNumber1 = "40691";
        String cardHolderName1 = "Charles";
        String cardNumber2 = "42689";
        String cardHolderName2 = "Sergio";
        Card testCard1 = new Card(cardNumber1, cardHolderName1);
        Card testCard2 = new Card(cardNumber2, cardHolderName2);
        ArrayList<Card> cards = new ArrayList<>();
        cards.add(testCard1);
        cards.add(testCard2);

        ArrayList<Card> empty = new ArrayList<>();
        Customer.readCustomers("resources/test_customers", empty);
        Customer.readCustomers("resources/test_customers.txt", cards);
        Customer.readCustomers("resources/test_customers.txt", empty);
    }

    @Test
    public void userInputTestSingleInstanceDelete() {
        int c_id = 1;
        int m_id = 1;
        String name = "Movie";
        String synopsis = "Synopsis";
        String rating = "G";
        String releaseDate = "10/10/2010";
        String actor1 = "Matt Damon";
        String actor2 = "Maaaaaatt Daaaaaamon";
        ArrayList<String> cast = new ArrayList<String>();
        cast.add(actor1);
        cast.add(actor2);
        Movie testMovie = new Movie(m_id, name, synopsis, rating, releaseDate, cast);
        ArrayList<Movie> moviesParent = new ArrayList<Movie>();
        moviesParent.add(testMovie);

        String c_name = "Event";
        String location = "Bondi Junction";

        int f_seatsCapacity = 50;
        int m_seatsCapacity = 50;
        int r_seatsCapacity = 50;
        String day = "Monday";
        String day2 = "Friday";
        LocalTime time = LocalTime.of(12, 00, 00, 00);
        LocalTime time2 = LocalTime.of(10, 00, 00, 00);
        String screenSize = "Gold";
        BigDecimal basePrice = new BigDecimal("20");

        MovieInstance movInst = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day, time, screenSize, basePrice);

        ArrayList<MovieInstance> movies = new ArrayList<>();
        movies.add(movInst);

        String username = "username";
        String password = "password";

        String cardNumber1 = "40691";
        String cardHolderName1 = "username";
        String cardNumber2 = "42689";
        String cardHolderName2 = "Sergio";
        Card testCard1 = new Card(cardNumber1, cardHolderName1);
        Card testCard2 = new Card(cardNumber2, cardHolderName2);
        ArrayList<Card> testCards = new ArrayList<Card>();
        ArrayList<GiftCard> validGiftCards = new ArrayList<GiftCard>();
        testCards.add(testCard1);
        testCards.add(testCard2);
        String testTicket1 = "Ticket1";
        String testTicket2 = "Ticket2";
        ArrayList<String> testTickets = new ArrayList<String>();
        testTickets.add(testTicket1);
        testTickets.add(testTicket2);

        Cinema testCinema2 = new Cinema(2, "swag cinema", "Swag Lake", movies, moviesParent);
        ArrayList<Cinema> cinemas = new ArrayList<>();
        cinemas.add(testCinema2);
        ArrayList<Cinema> cinemas2 = new ArrayList<>();
        cinemas2.add(testCinema2);
//[cinema_location]:[movie_name]:[day]:[time_HH] or 'cancel':\n"
        String input = "Swag Lake:Movie:Monday:12\n";
        // LocalDate.parse("11-11-2001");
        InputStream is = new ByteArrayInputStream(input.getBytes(StandardCharsets.UTF_8));
        UserInput u = new UserInput(is, System.out);
        ArrayList<Cinema> skux = u.promptSingleInstanceToDelete(cinemas);
        assertEquals(skux.size(), 1);
    }

    @Test
    public void userInputTestScreeningDay() {
        int c_id = 1;
        int m_id = 1;
        String name = "Movie";
        String synopsis = "Synopsis";
        String rating = "G";
        String releaseDate = "10/10/2010";
        String actor1 = "Matt Damon";
        String actor2 = "Maaaaaatt Daaaaaamon";
        ArrayList<String> cast = new ArrayList<String>();
        cast.add(actor1);
        cast.add(actor2);
        Movie testMovie = new Movie(m_id, name, synopsis, rating, releaseDate, cast);
        ArrayList<Movie> moviesParent = new ArrayList<Movie>();
        moviesParent.add(testMovie);

        String c_name = "Event";
        String location = "Bondi Junction";

        int f_seatsCapacity = 50;
        int m_seatsCapacity = 50;
        int r_seatsCapacity = 50;
        String day = "Monday";
        String day2 = "Friday";
        LocalTime time = LocalTime.of(12, 00, 00, 00);
        LocalTime time2 = LocalTime.of(10, 00, 00, 00);
        String screenSize = "Gold";
        BigDecimal basePrice = new BigDecimal("20");

        MovieInstance movInst = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day, time, screenSize, basePrice);

        ArrayList<MovieInstance> movies = new ArrayList<>();
        movies.add(movInst);

        String username = "username";
        String password = "password";

        String cardNumber1 = "40691";
        String cardHolderName1 = "username";
        String cardNumber2 = "42689";
        String cardHolderName2 = "Sergio";
        Card testCard1 = new Card(cardNumber1, cardHolderName1);
        Card testCard2 = new Card(cardNumber2, cardHolderName2);
        ArrayList<Card> testCards = new ArrayList<Card>();
        ArrayList<GiftCard> validGiftCards = new ArrayList<GiftCard>();
        testCards.add(testCard1);
        testCards.add(testCard2);
        String testTicket1 = "Ticket1";
        String testTicket2 = "Ticket2";
        ArrayList<String> testTickets = new ArrayList<String>();
        testTickets.add(testTicket1);
        testTickets.add(testTicket2);

        Cinema testCinema2 = new Cinema(2, "swag cinema", "Swag Lake", movies, moviesParent);
        ArrayList<Cinema> cinemas = new ArrayList<>();
        cinemas.add(testCinema2);
        ArrayList<Cinema> cinemas2 = new ArrayList<>();
        cinemas2.add(testCinema2);
        String input = "Tuesday\n";
        // LocalDate.parse("11-11-2001");
        InputStream is = new ByteArrayInputStream(input.getBytes(StandardCharsets.UTF_8));
        UserInput u = new UserInput(is, System.out);
        String input2 = "cancel\n";
        // LocalDate.parse("11-11-2001");
        InputStream is2 = new ByteArrayInputStream(input2.getBytes(StandardCharsets.UTF_8));
        UserInput u2 = new UserInput(is2, System.out);
        String output1 = u.promptScreeningDay();
        String output2 = u2.promptScreeningDay();

        assertEquals(output1, "Tuesday");
        assertEquals(output2, "cancel");
    }

    @Test
    public void userInputTestScreeningTime() {
        int c_id = 1;
        int m_id = 1;
        String name = "Movie";
        String synopsis = "Synopsis";
        String rating = "G";
        String releaseDate = "10/10/2010";
        String actor1 = "Matt Damon";
        String actor2 = "Maaaaaatt Daaaaaamon";
        ArrayList<String> cast = new ArrayList<String>();
        cast.add(actor1);
        cast.add(actor2);
        Movie testMovie = new Movie(m_id, name, synopsis, rating, releaseDate, cast);
        ArrayList<Movie> moviesParent = new ArrayList<Movie>();
        moviesParent.add(testMovie);

        String c_name = "Event";
        String location = "Bondi Junction";

        int f_seatsCapacity = 50;
        int m_seatsCapacity = 50;
        int r_seatsCapacity = 50;
        String day = "Monday";
        String day2 = "Friday";
        LocalTime time = LocalTime.of(12, 00, 00, 00);
        LocalTime time2 = LocalTime.of(10, 00, 00, 00);
        String screenSize = "Gold";
        BigDecimal basePrice = new BigDecimal("20");

        MovieInstance movInst = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day, time, screenSize, basePrice);

        ArrayList<MovieInstance> movies = new ArrayList<>();
        movies.add(movInst);

        String username = "username";
        String password = "password";

        String cardNumber1 = "40691";
        String cardHolderName1 = "username";
        String cardNumber2 = "42689";
        String cardHolderName2 = "Sergio";
        Card testCard1 = new Card(cardNumber1, cardHolderName1);
        Card testCard2 = new Card(cardNumber2, cardHolderName2);
        ArrayList<Card> testCards = new ArrayList<Card>();
        ArrayList<GiftCard> validGiftCards = new ArrayList<GiftCard>();
        testCards.add(testCard1);
        testCards.add(testCard2);
        String testTicket1 = "Ticket1";
        String testTicket2 = "Ticket2";
        ArrayList<String> testTickets = new ArrayList<String>();
        testTickets.add(testTicket1);
        testTickets.add(testTicket2);

        Cinema testCinema2 = new Cinema(2, "swag cinema", "Swag Lake", movies, moviesParent);
        ArrayList<Cinema> cinemas = new ArrayList<>();
        cinemas.add(testCinema2);
        ArrayList<Cinema> cinemas2 = new ArrayList<>();
        cinemas2.add(testCinema2);
        String input = "11:30\n";
        // LocalDate.parse("11-11-2001");
        InputStream is = new ByteArrayInputStream(input.getBytes(StandardCharsets.UTF_8));
        UserInput u = new UserInput(is, System.out);
        String input2 = "cancel\n";
        // LocalDate.parse("11-11-2001");
        InputStream is2 = new ByteArrayInputStream(input2.getBytes(StandardCharsets.UTF_8));
        UserInput u2 = new UserInput(is2, System.out);
        String output1 = u.promptScreeningTime("Monday");
        String output2 = u2.promptScreeningTime("Monday");

        assertEquals(output1, "11:30");
        assertEquals(output2, "cancel");
    }

    @Test
    public void userInputTestFireStaff() {
        int c_id = 1;
        int m_id = 1;
        String name = "Movie";
        String synopsis = "Synopsis";
        String rating = "G";
        String releaseDate = "10/10/2010";
        String actor1 = "Matt Damon";
        String actor2 = "Maaaaaatt Daaaaaamon";
        ArrayList<String> cast = new ArrayList<String>();
        cast.add(actor1);
        cast.add(actor2);
        Movie testMovie = new Movie(m_id, name, synopsis, rating, releaseDate, cast);
        ArrayList<Movie> moviesParent = new ArrayList<Movie>();
        moviesParent.add(testMovie);

        String c_name = "Event";
        String location = "Bondi Junction";

        int f_seatsCapacity = 50;
        int m_seatsCapacity = 50;
        int r_seatsCapacity = 50;
        String day = "Monday";
        String day2 = "Friday";
        LocalTime time = LocalTime.of(12, 00, 00, 00);
        LocalTime time2 = LocalTime.of(10, 00, 00, 00);
        String screenSize = "Gold";
        BigDecimal basePrice = new BigDecimal("20");

        MovieInstance movInst = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day, time, screenSize, basePrice);

        ArrayList<MovieInstance> movies = new ArrayList<>();
        movies.add(movInst);

        String username = "username";
        String password = "password";

        String cardNumber1 = "40691";
        String cardHolderName1 = "username";
        String cardNumber2 = "42689";
        String cardHolderName2 = "Sergio";
        Card testCard1 = new Card(cardNumber1, cardHolderName1);
        Card testCard2 = new Card(cardNumber2, cardHolderName2);
        ArrayList<Card> testCards = new ArrayList<Card>();
        ArrayList<GiftCard> validGiftCards = new ArrayList<GiftCard>();
        testCards.add(testCard1);
        testCards.add(testCard2);
        String testTicket1 = "Ticket1";
        String testTicket2 = "Ticket2";
        ArrayList<String> testTickets = new ArrayList<String>();
        testTickets.add(testTicket1);
        testTickets.add(testTicket2);
        ArrayList<Customer> customers = new ArrayList<Customer>();
        Customer g = new Customer("Staff1", "defstaffnotsus", null,null);
        customers.add(g);

        Cinema testCinema2 = new Cinema(2, "swag cinema", "Swag Lake", movies, moviesParent);
        ArrayList<Cinema> cinemas = new ArrayList<>();
        cinemas.add(testCinema2);
        ArrayList<Cinema> cinemas2 = new ArrayList<>();
        cinemas2.add(testCinema2);
        String input = "Staff1\n";
        InputStream is = new ByteArrayInputStream(input.getBytes(StandardCharsets.UTF_8));
        UserInput u = new UserInput(is, System.out);
        String output1 = u.promptRemoveStaff(customers);

        assertEquals(output1, "Staff1");
    }

    @Test
    public void userInputTestAddGiftCard() {
        GiftCard card = new GiftCard("1234567891123456GC", false);
        ArrayList<GiftCard> cards = new ArrayList<>();
        cards.add(card);

        String input = "1234567891123456GC\n";
        InputStream is = new ByteArrayInputStream(input.getBytes(StandardCharsets.UTF_8));
        UserInput u = new UserInput(is, System.out);
        String output1 = u.promptGiftCard(cards);

        assertEquals(output1, "1234567891123456GC");

        String input2 = "90123913\n1234567891123456GC";
        InputStream is2 = new ByteArrayInputStream(input2.getBytes(StandardCharsets.UTF_8));
        UserInput u2 = new UserInput(is2, System.out);
        String output2 = u2.promptGiftCard(cards);

        assertEquals(output2, "1234567891123456GC");
    }

    @Test
    public void userInputTestLocation() {
        int c_id = 1;
        int m_id = 1;
        String name = "Movie";
        String synopsis = "Synopsis";
        String rating = "G";
        String releaseDate = "10/10/2010";
        String actor1 = "Matt Damon";
        String actor2 = "Maaaaaatt Daaaaaamon";
        ArrayList<String> cast = new ArrayList<String>();
        cast.add(actor1);
        cast.add(actor2);
        Movie testMovie = new Movie(m_id, name, synopsis, rating, releaseDate, cast);
        ArrayList<Movie> moviesParent = new ArrayList<Movie>();
        moviesParent.add(testMovie);

        String c_name = "Event";
        String location = "Bondi Junction";

        int f_seatsCapacity = 50;
        int m_seatsCapacity = 50;
        int r_seatsCapacity = 50;
        String day = "Monday";
        String day2 = "Friday";
        LocalTime time = LocalTime.of(12, 00, 00, 00);
        LocalTime time2 = LocalTime.of(10, 00, 00, 00);
        String screenSize = "Gold";
        BigDecimal basePrice = new BigDecimal("20");

        MovieInstance movInst = new MovieInstance(m_id, c_id, testMovie, f_seatsCapacity, m_seatsCapacity, r_seatsCapacity,
                day, time, screenSize, basePrice);

        ArrayList<MovieInstance> movies = new ArrayList<>();
        movies.add(movInst);

        String username = "username";
        String password = "password";

        String cardNumber1 = "40691";
        String cardHolderName1 = "username";
        String cardNumber2 = "42689";
        String cardHolderName2 = "Sergio";
        Card testCard1 = new Card(cardNumber1, cardHolderName1);
        Card testCard2 = new Card(cardNumber2, cardHolderName2);
        ArrayList<Card> testCards = new ArrayList<Card>();
        ArrayList<GiftCard> validGiftCards = new ArrayList<GiftCard>();
        testCards.add(testCard1);
        testCards.add(testCard2);
        String testTicket1 = "Ticket1";
        String testTicket2 = "Ticket2";
        ArrayList<String> testTickets = new ArrayList<String>();
        testTickets.add(testTicket1);
        testTickets.add(testTicket2);
        ArrayList<Customer> customers = new ArrayList<Customer>();
        Customer g = new Customer("Staff1", "defstaffnotsus", null,null);
        customers.add(g);

        Cinema testCinema2 = new Cinema(2, "swag cinema", "Swag Lake", movies, moviesParent);
        ArrayList<Cinema> cinemas2 = new ArrayList<>();
        cinemas2.add(testCinema2);
        String input = "invalid\nSwag Lake\n";
        InputStream is = new ByteArrayInputStream(input.getBytes(StandardCharsets.UTF_8));
        UserInput u = new UserInput(is, System.out);
        String output1 = u.promptLocation(cinemas2);

        String input2 = "invalid\ncancel\n";
        InputStream is2 = new ByteArrayInputStream(input2.getBytes(StandardCharsets.UTF_8));
        UserInput u2 = new UserInput(is2, System.out);
        String output2 = u2.promptLocation(cinemas2);

        assertEquals(output1, "Swag Lake");
        assertEquals(output2, "cancel");

        movInst.setTicketPrice("bronze");
        movInst.setTicketPrice("silver");
        BigDecimal basePrice2 = new BigDecimal("16");
        movInst.setBasePrice(basePrice2);
        movInst.getBookings();
        movInst.getParent();
    }

    @Test
    public void giftCardTest() {
        String giftCardNumber = "1875890093350513";
        boolean redeemed = false;
        GiftCard testGiftCard = new GiftCard(giftCardNumber, redeemed);
        testGiftCard.readGiftCards("resources/test_giftcards.txt");
        testGiftCard.readGiftCards("");
    } 

}
